### ISSUE TITLE
Server does not run under Java8

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#103]
While testing with IntelliJ, I noticed some errors due to unknown methods.
I also tried to rebuild under Java8 and got some compilation errors.

**Comment by fbricon** [comment]
not it requires Java 11

**Comment by jeffmaury** [comment]
Then that's an issue as:
- it prevent Quarkus Tools for IntelliJ to be used on older versions of IJ
- it prevents Quarkus Tools for Eclipse to be used pre 2020-09

I understand the second is harder to fix but my PR will fix the first one

**Comment by fbricon** [comment]
JDT.LS depends on Java 11, so Eclipse pre 2020-09 is a non-starter
I'm really super not fond of the idea of targeting different JDKs for the different layers, ls vs jdt.ls.

I thought Quarkus was supposed to require Java 11 soon anyways. What's the status on that @maxandersen, @emmanuelbernard?

**Comment by jeffmaury** [comment]
Yes Quarkus requires Java11 but we are talking about the Java runtime that runs the IDE

**Comment by maxandersen** [comment]
We work with both versions but that's for runtime and build. 

The tooling still can support building / using Java 8 projects despite Ide require Java 11. 

Jeff. - how old / young versions of idea are we talking about that require Java 8?

**Comment by fbricon** [comment]
@maxandersen I know Quarkus still compiles/runs using Java 8 for now, but we were told Quarkus would soon require Java 11 minimum.
The point is, if Quarkus requires Java 11, then users have JDK 11, so no need to bother supporting Java 8 on the tooling side.

**Comment by angelozerr** [comment]
If it's really a problem, we could use java 8 for MicroProfile LS  and Java 11 for MicroProfile JDT?

**Comment by maxandersen** [comment]
What I'm saying is that quarkus have version is not really relevant. 

Question is what version of IntelliJ needs. 

Like if that is a 3 year old IntelliJ I don't care. If it's the current version (not) EAP I would be concerned.

**Comment by jeffmaury** [comment]
Seems Java11 is from 2019.2
Quarkus Tools for IntelliJ is compatible with 2019.1 +
As we are approaching 2020.3 I think it's fine to require 2019.2

**Comment by maxandersen** [comment]
So no problem ? ;)

**Comment by jeffmaury** [comment]
Yes we should be fine
