### ISSUE TITLE
@ConfigProperty validation when property is not set

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#146]
Given this @ConfigProperty:

```java
public class InventoryConfig {

    @ConfigProperty(name="port")
    private int port;

}
```
In this case the port property is not set (we can see that with hover).

It should be nice to highlight as an error (warn) that port is not set. It will give the capability:

 * to have an overwiew of several properties which are not set when we open the Java file
 * bind code actions to configure it. See https://github.com/eclipse/lsp4mp/issues/147

**Comment by datho7561** [comment]
Also make is so that you can ignore the warnings using a glob pattern

**Comment by rgrunber** [comment]
Not sure if anyone has run into this, but if I have a Quarkus project and annotate some field with `@ConfigProperty(name = "greeting.message")` and I refer to `greeting.message` in `application.properties`, I still get the `microprofile-config(NO_VALUE_ASSIGNED_TO_PROPERTY)` error, even though I'm clearly assigning it. It goes away if I define a defaultValue as expected. It also works as expected if I have a pure MicroProfile project (not Quarkus).

**Comment by angelozerr** [comment]
@rgrunber you need to save the application.properties. Because Java validation is retriggered when application.properties from target (not from sources) is done.

I don't know how to manage text edit and file save with code action.

**Comment by angelozerr** [comment]
> Not sure if anyone has run into this, but if I have a Quarkus project and annotate some field with @ConfigProperty(name = "greeting.message") and I refer to greeting.message in application.properties

Do you use last version of quarkus ls?

**Comment by rgrunber** [comment]
D'oh! You're absolutely right. I needed a quarkus-ls development build.

On the plus side, I also noticed that it's possible to test multiple extensions in the development host by supplying an additional :
`"--extensionDevelopmentPath=${workspaceFolder}/../vscode-microprofile"`
