### ISSUE TITLE
Exclude the method that's being annotated when showing completion for fallback method

### ISSUE THREAD

**Issue by datho7561** [eclipse/lsp4mp#148]
eg.

```java
@GET
@Produces(MediaType.TEXT_PLAIN)
@Fallback(fallbackMethod="|")
public String faultTolerant() {
    return "hello, world!";
}
```

If you trigger completion at the `|`, you shouldn't see `faultTolerant` suggested.

**Comment by rgrunber** [comment]
I wouldn't mind taking this if no one gets to it before me.

Entry point is probably in https://github.com/eclipse/lsp4mp/blob/master/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/faulttolerance/java/MicroProfileFaultToleranceCompletionParticipant.java#L82 . We need to compare the potential IMethod (to be included) with the fall back IAnnotation's parent (likely also an IMethod).
