### ISSUE TITLE
Do not rebuild list of configuration properties when MicroProfile config sources are updated in the build directory

### ISSUE THREAD

**Issue by datho7561** [eclipse/lsp4mp#162]
Background:
If you have a config source under `src/main/resources`, there will be another copy of the file representing the built application. For instance, in maven, this is usually under `target/classes`. microprofile-jdt uses the property values from this copy of the file in order to generate completion/validation/hover/etc. in Java files.

Currently, there is a listener defined in `MicroProfilePropertiesListenerManager` that detects a change to these files, and sends an event to microprofile-ls. This event has the same `MicroProfilePropertiesScope` as the event which causes microprofile-jdt to recalculate the list of all config properties by going through the Java files. Since they have the same `MicroProfilePropertiesScope`, microprofile-ls cannot distinguish between them, and must do both whenever it receives the event. This is bad, since calculating the list of all config properties from the Java files is computationally expensive.

Set up a new `MicroProfilePropertiesScope` to signify that one of the config sources has changed, and set it up so that this event only causes Java files to revalidate, and doesn't cause microprofile-jdt to recalculate the list of all properties.

**Comment by angelozerr** [comment]
After playing again with application.properties I noticed that a save of java file or a properties file provides 2 computes of properties from JDT side : 

 * one with source scope 
 * one with source + dependencies scope

It's too bad!

It should:

 * when a Java source file is saved recompute of properties should occur only from java sources.
 * when an application.properties file is saved recompute should never occur.

**Comment by rgrunber** [comment]
I think I noticed the same. Given how expensive it is to looks up values across an entire project (with many dependencies), we should limit it to source where possible. As long as a build file is not modified, is it safe to assume the dependencies cannot change (and so no need to recompute library properties) ?
