### ISSUE TITLE
Support microprofile-config-${profile}.properties

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#166]
Like we did for Quarkus LS ([support for application-${profile}](https://github.com/redhat-developer/quarkus-ls/pull/411)) we should support `microprofile-config-${profile}.properties`

See https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_on_config_source_level

**Comment by rzgry** [comment]
Is this a duplicate of https://github.com/eclipse/lsp4mp/issues/78 ?

**Comment by angelozerr** [comment]
> Is this a duplicate of #78 ?

Good catch!
