### ISSUE TITLE
Add setting to permit specific class return types for annotated methods

### ISSUE THREAD

**Issue by AlexXuChen** [eclipse/lsp4mp#170]
From https://github.com/eclipse/lsp4mp/pull/168#discussion_r696891424.

Quarkus allows `io.smallrye.mutiny.Uni` to be added at runtime with an `@Asynchronous` annotation, and so no diagnostic should be thrown when the annotated method returns type `io.smallrye.mutiny.Uni`.

To fix this problem, we should declare a setting ignore error(s) when the return type is included in a list of classes.

Blocked by #163

**Comment by rgrunber** [comment]
@angelozerr , do you know if we could also check the runtime for any additional classes supported in https://github.com/smallrye/smallrye-fault-tolerance/blob/main/implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/AsyncTypes.java#L22 (via ServiceLoader) ?

**Comment by angelozerr** [comment]
> do you know if we could also check the runtime for any additional classes

you mean with JDT?

**Comment by rgrunber** [comment]
In the Quarkus runtime itself. I wonder if we can check what other return types are being contributed since it seems it can be extended.

**Comment by angelozerr** [comment]
It means that we should starts the quarkus application to know that `io.smallrye.mutiny.Uni` is allowed?

**Comment by angelozerr** [comment]
If it that it means that validation will work only when quarkus application will be started, it's strange no?

**Comment by fbricon** [comment]
no, the quick n easy check is to verify is Uni is on the project classpath, if yes, allow it.

**Comment by angelozerr** [comment]
> no, the quick n easy check is to verify if Uni is on the project classpath, if yes, allow it.

Ok we hard code this class,  but if I create an impl of ReactiveTypeConverter and I regsiter it as SPI, it will not work.

**Comment by AlexXuChen** [comment]
For this setting, should we add default return types for the Asynchronous annotation specified by fault-tolerance? i.e. Future, CompletionStage, Uni

**Comment by angelozerr** [comment]
I think we should not managed Uni with settings, because it depends on project classpath, we should manage this Unit like JaxRsContext spirit. We could have a FaultToleranceContext which have a list of allowed class type. By default this list is filled with Future and CompletationStage. On Quarkus side we could contribute to this FaultToleranceContext  with Unit class.

**Comment by AlexXuChen** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/173/files#diff-92f5a9dc33e1ae679c0eb58e5d57a973a3df68e1da17ec2ecb624e0bfd24ad5fR95
