### ISSUE TITLE
Report diagnostic for @ConfigProperty(name="")

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#176]
Given a class with @ConfigProperty name attribute is empty:

```java
public class Foo {

  @ConfigProperty(name="")
  private String bar;

}
```

The Quarkus application throws this error :

![image](https://user-images.githubusercontent.com/1932211/132813417-69496ae2-1b63-4004-ba56-df257ac40e06.png)

We should report a diagnostic when name="" and it willfix too https://github.com/eclipse/lsp4mp/pull/167#discussion_r705496691

**Comment by AlexXuChen** [comment]
I can take this
