### ISSUE TITLE
Wrong annotation name for MicroProfile Metrics

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#186]
The Gauge annotation is referenced using org.eclipse.microprofile.metrics.Gauge where the correct name is org.eclipse.microprofile.metrics.annotation.Gauge

**Comment by angelozerr** [comment]
I remember that I fixed that. In master the problem is fixed https://github.com/eclipse/lsp4mp/blob/8531fee6cd5bb2fb60429f98d5bb72a432103258/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/metrics/MicroProfileMetricsConstants.java#L26 no?
