### ISSUE TITLE
SingleMemberAnnotation diagnostics not supported by annotationValidator

### ISSUE THREAD

**Issue by AlexXuChen** [eclipse/lsp4mp#188]
If we define a validator for the `@Timeout` annotation as follows:
```xml
<annotationValidator annotation="org.eclipse.microprofile.faulttolerance.Timeout"
                   source="microprofile-faulttolerance" >
   <attribute name="value" range="0" /> <!-- x >=0 -->
</annotationValidator>
```
then a range diagnostic will be properly thrown for the following incorrect range:
```java
@Timeout(value=-1)
```

However, you can also assign the `value` member without the member name, as follows:
```java
@Timeout(-1)
```
Currently, the above example cannot be caught by any configuration of the `annotationValidator` tag in `plugin.xml`.

**Comment by rgrunber** [comment]
Yup, looks like we're missing an edge case :

From  the javadoc :
```
Single member annotation node (added in JLS3 API). The single member annotation
"@foo(bar)" is equivalent to the normal annotation "@foo(value=bar)".
 ```

So in the validation logic, any single member annotation should have the `name=value` rule apply to it for the corresponding annotation.
