### ISSUE TITLE
JAXRS code lens participant based on method name range

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#194]
When generating the code lens, the JAXRS participant is computing the range based on the method name element which may lead to strange behavior for methods that are declared on several lines:

![image](https://user-images.githubusercontent.com/695993/136075251-b288d6e0-0acd-494b-be03-9ea31a0b8bed.png)

So on the IntelliJ implementation, I have used the whole method element to compute the range which gives this:

![image](https://user-images.githubusercontent.com/695993/136075818-f11e8c23-1421-4e3c-aa74-dc2a5da2a57a.png)

The fix is a single line of code change so let me know if you're interested by a PR

**Comment by rgrunber** [comment]
CC'ing @angelozerr . I think it makes sense! getParent() on the ASTNode to get the MethodDeclaration start line instead of the SimpleName ?

In the "method-on-single-line" case, it looks like we placed the codelens above the declaration but below the annotations. Does it make sense to preserve that behaviour ? Does anyone care ?

**Comment by angelozerr** [comment]
>I think it makes sense! getParent() on the ASTNode to get the MethodDeclaration start line instead of the SimpleName ?

Indeed we should improve that, but...

> Does it make sense to preserve that behaviour

It should be nice to keep that.

> Does anyone care ?

If I have time, I will do it.

**Comment by datho7561** [comment]
@JessicaJHee What do you think about this issue? If you are interested and are looking for an issue that won't take too long, I think it could be good. If you're not interested, I could also take a look into implementing it.
