### ISSUE TITLE
Support remaining date based ChronoUnit enumerations for `@Retry` annotation

### ISSUE THREAD

**Issue by AlexXuChen** [eclipse/lsp4mp#196]
As per https://github.com/eclipse/lsp4mp/pull/193#issuecomment-934591227:

We use `java.time.Duration` to calculate the difference between effective delay and max duration when passed as member values in the `@Retry` annotation. According to the implementation of `Duration.plus`, any date based `ChronoUnit` enumeration excluding `DAYS` (e.g. `WEEKS`, `MONTHS`, `YEARS`, etc..) will throw an `UnsupportedTemporalTypeException`.

Seeing that this is a limitation to the current implementation for `@Retry` diagnostics, (where we simply ignore these cases), there are 2 possible solutions:
1. Have a wrapper to handle every date based case
2. Wait for `java.time.Duration` to support date based enumeration(s)

**Comment by rgrunber** [comment]
Would this work ?

```
import java.time.temporal.ChronoUnit;
public double getDurationInNanos (ChronoUnit unit, long unitValue) {
  double seconds = (double) unit.getDuration().getSeconds();
  int nanos = unit.getDuration().getNano();
  return (seconds * 1000000000 * unitValue) + (nanos * unitValue);
}
```
```
jshell> getDurationInNanos(ChronoUnit.YEARS, 9) > getDurationInNanos(ChronoUnit.DECADES, 10)
$5 ==> false
jshell> getDurationInNanos(ChronoUnit.YEARS, 11) > getDurationInNanos(ChronoUnit.DECADES, 1)
$7 ==> true
```
