### ISSUE TITLE
Publish artifacts to p2 and Maven repo

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4mp#2]
- the jdt.ls extension needs to be accessible from a p2 repo, so it can be consumed downstream
- the microprofile.ls needs to be accessible from the Eclipse nexus repo, so it can be consumed downstream too

Need to setup the Jenkinsfile to make it happen in [Jenkins](https://ci.eclipse.org/lsp4mp/job/lsp4mp/).

**Comment by datho7561** [comment]
Hey Fred. Would you consider this issue complete?

**Comment by rgrunber** [comment]
I think it should be. JDT-LS is available as a p2 repo at http://download.eclipse.org/jdtls/milestones/1.2.0/repository/ and we do use it in the target platform of the lsp4mp OSGi bundles. microprofile.ls available under Nexus at https://repo.eclipse.org/content/repositories/lsp4mp/org/eclipse/lsp4mp/org.eclipse.lsp4mp.ls/ .
