### ISSUE TITLE
Definition hover displays properties defined below target property

### ISSUE THREAD

**Issue by AlexXuChen** [eclipse/lsp4mp#215]
As per https://github.com/redhat-developer/quarkus-ls/pull/458#issuecomment-981747909, hovering a property definition usinf `Ctrl + Hover` will display properties defined below the target property.

E.g. if you have an `application.properties` file as follows:
```
greeting.first=
greeting.message=
greeting.second=
```
The definition hover in the java file will display the following:
![Screenshot from 2021-11-29 10-31-55](https://user-images.githubusercontent.com/26389510/143897249-a9365cf5-0385-4d4b-a1f5-9af2fcd9124b.png)

**Comment by AlexXuChen** [comment]
Potential solution here is to remove the definition hover entirely, since there is already a hover tag for java feature participants: https://github.com/eclipse/lsp4mp/blob/bd97344aa464fec51984b6472e766c12972ce084/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/plugin.xml#L87

This would make the definition support purely for the navigation, since `Ctrl + Hover` will already display the hover, as shown above. Thoughts @rgrunber @angelozerr

**Comment by rgrunber** [comment]
Definition hover is useful when the primary hover is used for something like Javadoc. Then, the definition hover can show the actual location. In our case, if someone hovers over a property definition, there is only one thing we could show them, and that's the declaration in the properties file, which means that the definition hover becomes unnecessary.

**Comment by AlexXuChen** [comment]
Uncommenting https://github.com/eclipse/lsp4mp/blob/bd97344aa464fec51984b6472e766c12972ce084/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaFileTextDocumentService.java#L290
![image](https://user-images.githubusercontent.com/26389510/144447971-e5818c97-0c7d-4397-8b37-f64b98f4e879.png)
