### ISSUE TITLE
Setting "warning " on "microprofile.tools.validation.unknown.severity" is ignored

### ISSUE THREAD

**Issue by gian1200** [eclipse/lsp4mp#228]
### Issue

As described in https://github.com/redhat-developer/vscode-microprofile#supported-vs-code-settings, unknown properties should be flagged as Warning by default. However, they are flagged as Error.

Doc:
![image](https://user-images.githubusercontent.com/405347/161657119-9fb78818-6de1-499f-86fa-c85cf37f530f.png)

VSCode:
![image](https://user-images.githubusercontent.com/405347/161663109-a6523927-ad74-42bf-a22b-1e8dfccbea6b.png)

Even when forcing the value on Settings it is still ignored. The only way to make it work is to set all these 3 settings as "Warning" at the same time:

- `"microprofile.tools.validation.unknown.severity":"warning"`
- `"microprofile.tools.validation.expression.severity": "warning"`
- `"microprofile.tools.validation.value.severity": "warning"`

### Extensions version
- VSCode quarkus extension version: 1.10.0
![image](https://user-images.githubusercontent.com/405347/161294480-6af1d7c3-7116-4f71-968b-9567fa95ce77.png)

- Tools for MicroProfile version: 0.4.0
![image](https://user-images.githubusercontent.com/405347/161294440-c991af38-8445-4f3b-a67c-52ddf51aa847.png)

**Comment by AlexXuChen** [comment]
When trying to recreate this issue, it seems that the severity settings is configured properly on my side:
![Peek 2022-05-19 11-54](https://user-images.githubusercontent.com/26389510/169344381-7773ff2d-8b19-4465-879d-da35ca97c0e9.gif)
I configured these settings at the user level. Could you give me more detail on where you configured these severity settings?

**Comment by gian1200** [comment]
> Could you give me more detail on where you configured these severity settings?

I tested the changes using the UI and editing the json file.

Interesting, I just restested it and I got the same result you did on your gif (I'm on a different machine as to when I initially reported it, but same version of most things, except VSCode).

Just to be clear `Unknown referenced property` alert is not handled by `microprofile.tools.validation.unknown.severity`, right? (maybe I was confused by the wording and description).

I consider OK to have `microprofile.tools.validation.expression.severity` set as `error` by default and wouldn't like to lower it.
However, in this specific scenario the expression is not "wrong", the validator is just not currently designed to search the property definition at ENV OS level, so it shouldn't be an error.

Correct me if I'm wrong, `microprofile.tools.validation.unknown.severity` is only for unknown properties on the left side of the assignment operator (=), right? Is it possible to consider adding a new setting option for unknown propertes found on the right side of the assignment operator with default level `warning`?

**Comment by AlexXuChen** [comment]
> Just to be clear `Unknown referenced property` alert is not handled by `microprofile.tools.validation.unknown.severity`, right? (maybe I was confused by the wording and description).

Indeed, I believe there should be a differentiation in diagnostic message between `microprofile(unknown)` and `microprofile(expression)`. Thanks for bringing that to light!

> Correct me if I'm wrong, microprofile.tools.validation.unknown.severity is only for unknown properties on the left side of the assignment operator (=), right? Is it possible to consider adding a new setting option for unknown propertes found on the right side of the assignment operator with default level warning?

Yes, we handle `microprofile(unknown)` and `microprofile(expression)` separately.

**Comment by AlexXuChen** [comment]
> > Just to be clear `Unknown referenced property` alert is not handled by `microprofile.tools.validation.unknown.severity`, right? (maybe I was confused by the wording and description).
> 
> Indeed, I believe there should be a differentiation in diagnostic message between `microprofile(unknown)` and `microprofile(expression)`. Thanks for bringing that to light!

Should be improved in https://github.com/eclipse/lsp4mp/pull/242

**Comment by AlexXuChen** [comment]
> However, in this specific scenario the expression is not "wrong", the validator is just not currently designed to search the property definition at ENV OS level, so it shouldn't be an error.

Should be fixed in #247

**Comment by angelozerr** [comment]
@AlexXuChen I tink we can close this issue?

**Comment by angelozerr** [comment]
This issue should now fixed.
