### ISSUE TITLE
Add support for jakarta namespace

### ISSUE THREAD

**Issue by yeekangc** [eclipse/lsp4mp#229]
MP 5 supports jakarta namespace aligning with Jakarta EE 9/9.1.  The LS should support the use of packages with the jakarta namespace.

Cc @kathrynkodama

**Comment by angelozerr** [comment]
Is it possible to explain more which support you wish to have with a sample please.

**Comment by angelozerr** [comment]
Ok I see, thanks @kathrynkodama for your feedback. Any contribution are welcome :)

**Comment by datho7561** [comment]
Another part of this issue, which I've start to look at in https://github.com/eclipse/lsp4mp/pull/313, is making sure that the CodeLens for JAX-RS and RestClient appear in cases where `Path` and `GET` are imported using the jakarta namespace.
