### ISSUE TITLE
ASTValidator uses IDE classpath instead of project classpath

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#232]
See https://github.com/eclipse/lsp4mp/blob/f54b7355be2797ec8843e7d106cb4af0296a2ba6/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/config/java/MicroProfileConfigASTValidator.java#L248

**Comment by rgrunber** [comment]
Right. Using the project classpath would likely require us to look very closely at the performance, as we'd essentially be querying the index for the value.

We likely want to do [`JDTTypeUtils.findType(IJavaProject, String)`](https://github.com/eclipse/lsp4mp/blob/master/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/utils/JDTTypeUtils.java#L43)
