### ISSUE TITLE
MicroProfileConfigASTValidator may use prefix from annotation which is not @ConfigProperties

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#233]
https://github.com/eclipse/lsp4mp/blob/f54b7355be2797ec8843e7d106cb4af0296a2ba6/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/config/java/MicroProfileConfigASTValidator.java#L109

**Comment by angelozerr** [comment]
Yes I think so.
