### ISSUE TITLE
Rename profile parameter to ordinal for better readability

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#236]
https://github.com/eclipse/lsp4mp/blob/f54b7355be2797ec8843e7d106cb4af0296a2ba6/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/project/PropertiesConfigSource.java#L42

**Comment by rgrunber** [comment]
Definitely a confusing typo given that there is already a `String profile` field in the base type.
