### ISSUE TITLE
Properties support for microprofile-reactive-messaging

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#26]
https://github.com/eclipse/microprofile-reactive-messaging/blob/62c9ed5dffe01125941bb185f1433d6307b83c86/spec/src/main/asciidoc/architecture.asciidoc#configuration

https://quarkus.io/guides/kafka#configuring-the-kafka-connector

**Comment by angelozerr** [comment]
@rzgry thanks for having created the issue. I will work on this support, see https://github.com/redhat-developer/vscode-quarkus/issues/218 for more information.

**Comment by rzgry** [comment]
> @rzgry thanks for having created the issue. I will work on this support, see [redhat-developer/vscode-quarkus#218](https://github.com/redhat-developer/vscode-quarkus/issues/218) for more information.

Ah didn't realize there was already an issue under vscode-quarkus. Good to have this issue here as well for tracking.
