### ISSUE TITLE
Properties support for microprofile-graphql

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#27]
Graphql error handling managed by microprofile config

https://github.com/eclipse/microprofile-graphql/blob/905456693d9bfb1f78efe0d7e614db6fde3324b2/server/spec/src/main/asciidoc/errorhandling.asciidoc

List of config keys: 
https://github.com/eclipse/microprofile-graphql/blob/master/server/api/src/main/java/org/eclipse/microprofile/graphql/ConfigKey.java

**Comment by kathrynkodama** [comment]
I can pick this up

**Comment by angelozerr** [comment]
> I can pick this up

Thanks!
