### ISSUE TITLE
Snippet variable not replaced with actual value

### ISSUE THREAD

**Issue by mezarin** [eclipse/lsp4mp#282]
We have an Eclipse IDE client implementation making use of lsp4mp. When using the completion/snippet action, the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) defined set of “default” variables (i.e. TM_FILENAME_BASE) used  by the lsp4mp provided snippets  are not replaced with actual values. 

For example, if I press Ctrl + space and choose the `mpreadiness` option, I get this:
```
package dev.test;
…
@Readiness
@ApplicationScoped
public class ${TM_FILENAME_BASE} implements HealthCheck {

	@Override
	public HealthCheckResponse call() {
		return HealthCheckResponse.named(${TM_FILENAME_BASE}.class.getSimpleName()).withData("ready",true).up().build();
	}

```

As a point of comparison, I also installed the [Eclipse IDE jbosstools-quarkus](https://github.com/jbosstools/jbosstools-quarkus) client, installed my application, created a new class, pressed ctrl+ space, and chose `mpreadiness`. The same issue occurs there.

What is interesting though is the fact that if install the [vscode-microprofile](https://github.com/redhat-developer/vscode-microprofile) client, the issue does not show there. I took a quick peek at that code, and it appears that that code registers it’s own completion item provider; however, it is not clear to me if that (workaround?) is what is causing the “default” variables to be replaced correctly.

**Comment by rgrunber** [comment]
According to https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionClientCapabilities .
```
/**
* Client supports snippets as insert text.
*
* A snippet can define tab stops and placeholders with `$1`, `$2`
* and `${3:foo}`. `$0` defines the final tab stop, it defaults to
* the end of the snippet. Placeholders with equal identifiers are
* linked, that is typing in one will update others too.
*/
snippetSupport?: boolean;
```

which is sent as part of the client's `initialize()` request to the server. That would indicate the client must inform the server whether it supports snippets.

Here's what I see as a sample interaction on the vscode-microprofile side :

```
[Trace - 3:33:47 p.m.] Sending request 'textDocument/completion - (165)'.
Params: {
    "textDocument": {
        "uri": "file:///home/rgrunber/sample-projects/my-quarkus-example/src/main/java/org/example/Test.java"
    },
    "position": {
        "line": 0,
        "character": 11
    },
    "context": {
        "triggerKind": 1
    }
}
```

```
[Trace - 3:33:48 p.m.] Received response 'textDocument/completion - (165)' in 27ms.
Result: {
    "isIncomplete": false,
    "items": [
        {
            "label": "mpreadiness",
            "kind": 15,
            "detail": "MicroProfile Health readiness check",
            "documentation": {
                "kind": "markdown",
                "value": "\n```\npackage org.example;\n\nimport org.eclipse.microprofile.health.HealthCheck;\nimport org.eclipse.microprofile.health.HealthCheckResponse;\nimport org.eclipse.microprofile.health.Readiness;\n\nimport javax.enterprise.context.ApplicationScoped;\n\n@Readiness\n@ApplicationScoped\npublic class TM_FILENAME_BASE implements HealthCheck {\n\n\t@Override\n\tpublic HealthCheckResponse call() {\n\t\treturn HealthCheckResponse.named(TM_FILENAME_BASE.class.getSimpleName()).withData(\"ready\",true).up().build();\n\t}\n}\n```\n"
            },
            "filterText": "mpreadiness",
            "insertTextFormat": 2,
            "textEdit": {
                "range": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 11
                    }
                },
                "newText": "package org.example;\n\nimport org.eclipse.microprofile.health.HealthCheck;\nimport org.eclipse.microprofile.health.HealthCheckResponse;\nimport org.eclipse.microprofile.health.Readiness;\n\nimport javax.enterprise.context.ApplicationScoped;\n\n@Readiness\n@ApplicationScoped\npublic class ${TM_FILENAME_BASE} implements HealthCheck {\n\n\t@Override\n\tpublic HealthCheckResponse call() {\n\t\treturn HealthCheckResponse.named(${TM_FILENAME_BASE}.class.getSimpleName()).withData(\"ready\",true).up().build();\n\t}\n}"
            }
        },
        ...
        ...
    ]
}
```
If I apply the completion, it resolves correctly, so the client must be required to handle this. However, I did just notice that the javadoc uses `TM_FILENAME_BASE` as the name and fails to resolve which is wrong. I think this might be a separate issue where it isn't properly applied except to the text of a completion item.

**Comment by angelozerr** [comment]
Perhaps it is a bug with LSP4E. The code which support TM_FILENAME_BASE is here https://github.com/eclipse/lsp4e/blob/8cacdfd4a48ebdb450d678c33dfb20556c330221/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java#L634

and getVariableValue is called only at https://github.com/eclipse/lsp4e/blob/8cacdfd4a48ebdb450d678c33dfb20556c330221/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java#L507

and this below code is called if the following condition is matched :

https://github.com/eclipse/lsp4e/blob/8cacdfd4a48ebdb450d678c33dfb20556c330221/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java#L504

Perhaps it is a problem with isChoice. In our usecase we use TM_FILENAME_BASE  without choice (without list a of values sperataed with |)

I suggest that youcreate an issue at https://github.com/eclipse/lsp4e/issues

**Comment by mezarin** [comment]
@rgrunber @angelozerr, thanks for the quick responses. Things are a bit clearer now. I will open an lsp4e repo issue.
