### ISSUE TITLE
Support for the config_ordinal property in microprofile-config.properties

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4mp#289]
The `config_ordinal` is flagged as an "unknown property":
<img width="739" alt="image" src="https://user-images.githubusercontent.com/26146482/190660799-28076b8f-261b-4d7c-9774-615342eaa973.png">
but defined in the spec: https://download.eclipse.org/microprofile/microprofile-config-1.4/microprofile-config-spec.html#_manually_defining_the_ordinal_of_a_built_in_configsource

**Comment by rgrunber** [comment]
The property certainly works for me on a simple project if I try to override the ordinals at https://quarkus.io/guides/config-reference#configuration-sources . Maybe we just need to add it as a static property.

**Comment by angelozerr** [comment]
Indeed it is the idea but we need to provide it according the version of the MP.
