### ISSUE TITLE
"Unknown property" maybe should be described as "unused"?

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4mp#290]
**EDIT:**  I updated this after seeing #289 opened to avoid duplication and only cover what's left of my original issue:

## unused vs. unknown

I think the "unused" adjective might be a better description than "unknown".

My first reaction is: "what do you mean it's unknown?   I'm telling you this is the value."  :)  

OTOH, in Eclipse or VSCode, if I just declare a local variable 'x' without referencing it, I get the message (guessing from JDT LS?): 
`The value of the local variable 'x' is not used.`

So "unused" or to spell it out more "appears to be unused in a MicroProfile Config injection into a Java class" (if it's worth spelling it out more... though not sure it is).

**Comment by rgrunber** [comment]
I think "unknown" was meant in the sense that it is unknown to the framework, and won't do anything unless it is used. Maybe we need the message to be a combination of both.

@angelozerr thoughts ?

**Comment by angelozerr** [comment]
I used unkwonw because it is unkwonw for microprofile or quarkus framework.

But if yiu think it is better to change with unused we can change that.

@fbricon what do you think about that?
