### ISSUE TITLE
ClassCastException thrown (and caught) when using invalid @ConfigProperty defaultValue

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lsp4mp#295]
- Provide something like : `@ConfigProperty(name = "greeting.suffix", defaultValue = 1213)`

https://github.com/eclipse/lsp4mp/blob/b8c6d0651ae7c59f137a59a240fde3f40874a2ca/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/config/java/MicroProfileConfigASTValidator.java#L166

`defaultValueExpr` may not necessarily be a `StringLiteral`. The error is caught at https://github.com/eclipse/lsp4mp/blob/b8c6d0651ae7c59f137a59a240fde3f40874a2ca/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/java/validators/MultiASTVisitor.java#L72 .

Also @datho7561 , why can't I find this error logged anywhere ?

**Comment by datho7561** [comment]
Is it in the eclipse.jdt.ls logs anywhere?

**Comment by datho7561** [comment]
eclipse.jdt.ls/JDT has it's own logging system, right? Maybe we need to use that one instead of java.util.logging

**Comment by rgrunber** [comment]
Maybe @JessicaJHee , could take this, since she ran into a similar case for https://github.com/eclipse/lsp4mp/pull/294#discussion_r986024759
