### ISSUE TITLE
MicroProfileConfigASTValidator handles @ConfigProperties in a wrong way

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#304]
`MicroProfileConfigASTValidator` tries to locate `@ConfigProperties` but it uses only the simple class name and not the fully qualified class name.
As a result, it also works for Quarkus `@ConfigProperties` but it should located into the Quarkus specific part and it may wrongly process `@ConfigProperties` annotations from other packages.

**Comment by rgrunber** [comment]
When I look at https://github.com/eclipse/lsp4mp/blob/8ccfef8087a3279bcb15cf92f9d093e861dd4d19/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/config/java/MicroProfileConfigASTValidator.java#L109 it's using https://github.com/eclipse/lsp4mp/blob/8ccfef8087a3279bcb15cf92f9d093e861dd4d19/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/MicroProfileConfigConstants.java#L41 , which is fully qualified.

I think quarkus-ls has a separate properties provider to handle ConfigProperties from that end also.

**Comment by jeffmaury** [comment]
Yes agree but if you go into `isMatchAnnotation` you will find that the annotation type name is ConfigProperties and not the fully qualified name
See my Eclipse debugging session:

![image](https://user-images.githubusercontent.com/695993/197699849-df9922b0-2a65-45ce-8cd1-836491d21acd.png)

**Comment by rgrunber** [comment]
Interesting, so immediately above that is line 186, which is `AnnotationUtils.isMatchAnnotation(..)`

https://github.com/eclipse/lsp4mp/blob/8ccfef8087a3279bcb15cf92f9d093e861dd4d19/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/utils/AnnotationUtils.java#L186

So `annotation.getTypeName().getFullyQualifiedName()` is not returning the fully qualified name. Is there any chance the annotation element is not resolved ? Definitely a bug. Would need to investigate to figure out what's going wrong with the annotation.

**Comment by jeffmaury** [comment]
> Interesting, so immediately above that is line 186, which is `AnnotationUtils.isMatchAnnotation(..)`
> 
> https://github.com/eclipse/lsp4mp/blob/8ccfef8087a3279bcb15cf92f9d093e861dd4d19/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/utils/AnnotationUtils.java#L186
> 
> So `annotation.getTypeName().getFullyQualifiedName()` is not returning the fully qualified name. Is there any chance the annotation element is not resolved ? Definitely a bug. Would need to investigate to figure out what's going wrong with the annotation.

Yes because `getTypeName()` returns a SimpleName probably because the annotation is referenced through `@ConfigProperties` and not the FQCN

**Comment by datho7561** [comment]
I created https://github.com/redhat-developer/quarkus-ls/issues/759 to talk/fix this. Maybe the right solution is not validating the Quarkus `@ConfigProperties` at all, but either way, we should remove the tests in lsp4mp that reference it.
