### ISSUE TITLE
`config_ordinal` appears as a property even in non-MicroProfile projects

### ISSUE THREAD

**Issue by datho7561** [eclipse/lsp4mp#312]
To reproduce (I used vscode-microprofile:)

1. Open a non-MicroProfile project (I used eclipse/lemminx) that has a `.properties` file (any `.properties` file not necessarily a MicroProfile one).
2. Get your editor to detect that the the `.properties` file is a MicroProfile config file so that the language server activates.
3. Open completion at the beginning of a blank line
4. You should get `config_ordinal` suggested

**Comment by rgrunber** [comment]
I think originally when I reviewed this change, I allowed @JessicaJHee to have it enabled all the time. Maybe we could use the new `typeOnClasspath` attribute to check that a class is actually on the classpath.
