### ISSUE TITLE
MicroProfileHealthDiagnosticsParticipant incompatible with MicroProfile Health 3.0 and later

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/lsp4mp#314]
https://github.com/eclipse/lsp4mp/blob/2d7d129f545151f123ff935893a0853959164d34/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/health/java/MicroProfileHealthDiagnosticsParticipant.java#L75

**Comment by rgrunber** [comment]
Yup, https://download.eclipse.org/microprofile/microprofile-health-3.0/microprofile-health-spec-3.0.html#_different_kinds_of_health_checks , should be easy to either check any of the 3 (Health, Readiness, Liveness), or the HealthCheck type.

**Comment by jeffmaury** [comment]
`Health` should not be used because it has been removed, that's the point

**Comment by rgrunber** [comment]
If we don't need to maintain any compatibility for 2.0, then yes, we can just remove that.

**Comment by jeffmaury** [comment]
We need to support 2.0 as well as 3.0 but this can be achieved by using `Liveness`, `Readiness` or `HeathCheck` rather than a deprecated annotation type to detect MicroProfile Health for the project.
