### ISSUE TITLE
The proposal description is not clear

### ISSUE THREAD

**Issue by gkwan-ibm** [eclipse/lsp4mp#323]
The proposal description is not clear, e.g.

1. do not know where the annotation from. Suggest to indicate which MP / Jakarta EE feature. See following example that tells which JUnit
    -  ![Screen Shot 2022-11-16 at 8 36 15 AM](https://user-images.githubusercontent.com/29576299/203405099-72969e45-77af-4025-9789-61cccc52b351.png)

2. should tell to apply on method, class, variable, or … 
3. description pattern and format is not consistent
4. can the code having code style like following?
    - ![Screen Shot 2022-11-16 at 8 26 19 AM](https://user-images.githubusercontent.com/29576299/203405391-45f54c8e-135b-4477-b98a-34af44bf1f9c.png)
5. can have a space line between the description and the code?

**Comment by angelozerr** [comment]
@gkwan-ibm could you add a screenshot with `MP / Jakarta EE feature`  please just to understand more what is not clear and suggets us some improvement (ex : do not know where the annotation from. , what is your exact suggestion)

**Comment by angelozerr** [comment]
> do not know where the annotation from. Suggest to indicate which MP / Jakarta EE feature. See following example that tells which JUnit

The description popup is not enought? Please give us in detail your suggestion.

> should tell to apply on method, class, variable, or …

Totally agree, but it is not trivial because it will require to trigger JDT LS on each key stroke and retrieve with JDT if you are before / inside / after a method, inside an annotation, etc is not easy. See https://github.com/eclipse/lsp4mp/issues/108#issuecomment-733738735

> description pattern and format is not consistent

Could you give us a sample please.

> can the code having code style like following?

At first it is not an issue for LSP4MP, but for LSP4E (syntax coloration for markdown renderer of a given code)

In vscode, it works perfectly, because the editor content and the popup uses the same syntax coloration : TextMate grammar.

So I suggest that you create an issue in LSP4E.

> can have a space line between the description and the code?

Could you add a screenshot please and tell us where you need a space?

**Comment by gkwan-ibm** [comment]
screenshot from Mac:
![Screen Shot 2022-11-23 at 11 28 22 AM](https://user-images.githubusercontent.com/29576299/203598685-73ca955b-5dfe-4fe7-b25a-85204f86f711.png)
- In between the first line and the code, it is better to have an empty line

**Comment by gkwan-ibm** [comment]
screenshots from Mac
![Screen Shot 2022-11-23 at 11 28 38 AM](https://user-images.githubusercontent.com/29576299/203599273-89f3fa83-f028-4404-9921-3402b2d1d763.png)
![Screen Shot 2022-11-23 at 11 28 48 AM](https://user-images.githubusercontent.com/29576299/203599291-d1080919-7126-4dff-8380-b89911e6bb03.png)

- there are multiple `@Content` and `@Schema`. It is better to have more text for users to distinguish the different. Like the JUnit example in this issue description

**Comment by fbricon** [comment]
Adding a line between the description and the body of the change is something that needs to be fixed in LSP4E, nothing we can do here.

**Comment by gkwan-ibm** [comment]
![Screen Shot 2022-11-23 at 11 35 35 AM](https://user-images.githubusercontent.com/29576299/203600077-a04de1af-cd48-4a31-a9ea-d94ba658fc86.png)

- the first line description is very simple. It is better to tell users that this annotation should be applied on a method, class, or variable, as well as it is from which MP feature

**Comment by gkwan-ibm** [comment]
> Adding a line between the description and the body of the change is something that needs to be fixed in LSP4E, nothing we can do here.

created https://github.com/eclipse/lsp4e/issues/317

**Comment by gkwan-ibm** [comment]
![Screen Shot 2022-11-23 at 11 46 01 AM](https://user-images.githubusercontent.com/29576299/203602299-2f9449f7-7f4c-4ff2-9141-0af4fe31c0e0.png)

- an example of how clear the description. The annotation description should have its pattern and set of information

**Comment by angelozerr** [comment]
I close this issue since it is an LSP4E issue.
