### ISSUE TITLE
Diagnostics for mp-fault-tolerance fallbackMethod

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#33]
Would be nice to validate if fallback method exists. Or if it doesnt maybe provide a quick fix to create the fallback method.

Ex. would be good to catch that their is a typo here in the fallback method (`falback` instead of `fallback`)

<img src="https://user-images.githubusercontent.com/16768710/88943724-d672ee00-d259-11ea-8002-24fce0b77d6a.png" width="500px">

**Comment by datho7561** [comment]
I would be interested on working on this issue.
