### ISSUE TITLE
Completion for mp-fault-tolerance fallbackMethod

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#34]
Would be nice to provide completion fallback method completion.

Ex : fallbackMethod="|" should provide fallback:

<img src="https://user-images.githubusercontent.com/16768710/88943724-d672ee00-d259-11ea-8002-24fce0b77d6a.png" width="500px">

**Comment by datho7561** [comment]
I would be interested in working on this

**Comment by rzgry** [comment]
Thanks @datho7561 🙂
