### ISSUE TITLE
MicroProfile rest client diagnostic using incorrect EE level

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4mp#344]
Using a project with MP 5 and EE 9 in VS Code (generated with https://start.microprofile.io/)
See the following class, the MP REST client diagnostic appears even though the `@Inject` annotation is already present (but using `jakarta.inject.Inject`)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26146482/212987705-10104623-300b-495f-a1b4-7e4b4a887ba0.png">

Selecting the quick-fix inserts the `javax.inject.Inject` annotation:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/26146482/212987745-402fe832-17d3-4e2f-9b47-4244854f0cde.png">
<img width="775" alt="image" src="https://user-images.githubusercontent.com/26146482/212987808-c04cd91a-20a8-4421-9a92-7edb348f82e6.png">

**Comment by angelozerr** [comment]
@kathrynkodama is there any chance that you fix this issue?

**Comment by kathrynkodama** [comment]
@angelozerr I am glad to take a look at the issue when I have a spare cycle.

**Comment by fbricon** [comment]
It's likely similar issues will occur in other places. Snippets / Code Actions code needs to be reviewed all around.

**Comment by angelozerr** [comment]
@kathrynkodama have the intention to work on this issue soon? Otherwise @JessicaJHee could be interested to work on it.

**Comment by kathrynkodama** [comment]
Please go ahead, I am not able to pick up this issue this week. Thank you @JessicaJHee @angelozerr

**Comment by datho7561** [comment]
@JessicaJHee going back to what Fred mentioned about finding other places that javax is mentioned instead of jakarta, there is a class file `MicroProfileMetricsConstants` that references the `javax` namespace, so take a look into how those are used, and see if there is a way we could use jakarta instead.

**Comment by datho7561** [comment]
Found some more :disappointed: (will update as I go through the codebase):
- [ ] OpenAPIAnnotationProposal: on line 67 we check for `JaxRsConstants.JAVAX_WS_RS_RESPONSE_TYPE` but not the corresponding `jakarta` namespace type

**Comment by datho7561** [comment]
As far as I know, we should now support all the features with both the `javax` and `jakarta` namespaces. Thanks so much, Jessica! Also @kathrynkodama, let me know if you run into any other cases of features that aren't working with the `jakarta` namespace.
