### ISSUE TITLE
Completion uses the last character as context to filter among proposals instead of the last "word"

### ISSUE THREAD

**Issue by scottkurz** [eclipse/lsp4mp#368]
## Env:  

I tested with a few environments:

* 2022-12, Eclipse for Java package, plus Quarkus Tools from Eclipse Marketplace
* Liberty Tools Eclipse - a local branch build using LSP4MP 0.6
* 2023-03-RC1, Eclipse for Java package... (. I think I ended up just using Quarkus Tools from Eclipse Marketplace.   I tried to build and install locally from master but that had some missing content so I just installed from Eclipse Marketplace over it).

I believe all three use LSP4MP 0.6..I know the first two do.

## Details

In this example I have a  `@Inject MyAppBean bean;` already in the class to show what I'm trying to type (a 2nd field of the same type).

When I hit Ctrl+Space after `my` I get these proposals:
![image](https://user-images.githubusercontent.com/4081634/223229234-4518d4dc-a2fc-468c-a9b3-e8726eb0c135.png)

then when I hit Ctrl+Space after `mya` I get these proposals:
![image](https://user-images.githubusercontent.com/4081634/223229253-fc2498d8-8d5c-4db7-ac7f-0169e05ce0a2.png)

If I continue it's clear that the filtering is happening via the very last char that I typed.  

On the other hand, if I just rely on normal completion in Eclipse (from the JDT) without MP LS, the filtering takes into account the whole last "word" (and shows it in bold).

So if I have a very common letter like 's', I might get a lot of proposals, which is confusing if I think I've typed enough chars of my string that there should only be a very few # of proposals.

## OTHER CONTEXT

We dealt with a similar issue in Liberty Tools (Eclipse) for the Jakarta LS, where the problem was dealt with on the server side by an additional filter: https://github.com/eclipse/lsp4jakarta/pull/386

Also, on a totally different note, I see the LSP spec says:
>     to achieve consistency across languages and to honor different clients usually the client is responsible for filtering and sorting

Not sure what to make of all that.  Would be interesting to hear your thoughts.

**Comment by datho7561** [comment]
> the client is responsible for filtering and sorting

In VS Code, VS Code itself filters the completion items instead of lsp4mp. This prevents having to do a round trip to the server to update the completion list on every keystroke. It would be nice if lsp4e also provided support for this, especially given the wording of the specification.

**Comment by angelozerr** [comment]
@scottkurz please report your issue on LSP4E https://github.com/eclipse/lsp4e/issues
