### ISSUE TITLE
Edits to MicroProfile Config Source files do not get reflected in the IDE

### ISSUE THREAD

**Issue by dshimo** [eclipse/lsp4mp#380]
`getConfigSources()` in `PsiMicroProfileProject.java` currently initializes config sources once and returns those values regardless. Creating a new properties file or renaming it don't get reflected in the IDE. This produces noticeable bugs with the `NO_VALUE_ASSIGNED_TO_PROPERTY` diagnostic and quick fixes.

![image](https://user-images.githubusercontent.com/8934136/229910534-2e55cf3d-ee86-4aea-a832-b1c7e4479f49.png)

Originally named `META-INF/microprofile-config.properties`, the quick fix worked as intended. Renaming or moving the properties file will not affect the quick fix label, and clicking the quickfix will continue to insert the property to the file.

![image](https://user-images.githubusercontent.com/8934136/229912348-ae0ae795-1312-4779-af7d-b4d2d5733b57.png)

**Comment by datho7561** [comment]
@sbouchet @adietish this might be related to code in intellij-quarkus

**Comment by dshimo** [comment]
Oh my mistake!! This the wrong repo
