### ISSUE TITLE
Don't compute/send quickfixes requiring client commands, if the client doesn't support those

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4mp#387]
In intellij-quarkus, I can see quick fixes for unknown properties, as they're returned by lsp4mp, but they're ineffective, as the intellij client doesn't yet support the underlying command (see https://github.com/redhat-developer/intellij-quarkus/issues/811)

<img width="687" alt="Screenshot 2023-04-21 at 16 27 32" src="https://user-images.githubusercontent.com/148698/233662123-a179031a-997d-433a-bf72-76b301f53c12.png">

Some of these quickfixes should be guarded behind a client capability, and not computed if the client doesn't support the required capability.

**Comment by angelozerr** [comment]
MP LS support that, It is a bug from IJ Quarkus, I created the PR https://github.com/redhat-developer/intellij-quarkus/pull/814
