### ISSUE TITLE
Improve completion performance in properties files

### ISSUE THREAD

**Issue by JessicaJHee** [eclipse/lsp4mp#389]
This requires two changes:
1. Implement resolve for documentation
2. Implement `itemDefaults` for `completionList` to reduce the size of the completion result. See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionList

**Comment by angelozerr** [comment]
I suggest that you start to implement the 1.

**Comment by JessicaJHee** [comment]
From my testing, the performance improvement in the LS response time is as follows:

|  | 1st run | 2nd run | 3rd run | Average|
| ------------- | ------------- | ------------- | ------------ | ------------ | 
| Before change  | 137ms | 141ms | 118ms | 132ms |
| After change | 91ms | 85ms | 88ms | 88ms |

Outside of this, there is a visible difference on the client side to actually display the completion result since the `textDocument/completion` response is much smaller now.

**Comment by angelozerr** [comment]
Thanks @JessicaJHee for youŕ feedback. Great job!
