### ISSUE TITLE
Add support for @Startup healthcheck diagnostic

### ISSUE THREAD

**Issue by michelcouto** [eclipse/lsp4mp#443]
When having a class implementing `org.eclipse.microprofile.health.HealthCheck` and using the `@Startup` annotation brought since 3.1 API, Eclipse shows the following warning:
The class com.acme.SomeStartupHealthCheck implementing the HealthCheck interface should use the `@Liveness` or `@Readiness` annotation.

`@Startup` should also be supported!

**Comment by fbricon** [comment]
Can you provide some pointers to the spec?

**Comment by michelcouto** [comment]
Sure.
https://download.eclipse.org/microprofile/microprofile-health-3.1/apidocs/

See that, since 3.1, alongside Readiness and Liveness annotations, supported by the MicroProfile Language Server, there is then the Startup one as well.

https://github.com/eclipse/microprofile-health
In here, there are talks about the 3 different checks (startup, live and ready).
