### ISSUE TITLE
Update to the latest jdt-ls

### ISSUE THREAD

**Issue by datho7561** [eclipse/lsp4mp#446]
I think we need to use the latest jdt.ls, since the i builds that the older version references have been deleted.

**Comment by rgrunber** [comment]
Yup, the 1.36.0 snapshots of JDT-LS probably point to an I-build of 4.32, and as soon as the GA hits, they git rid of the I-builds. Had to update in JDT-LS, https://github.com/eclipse-jdtls/eclipse.jdt.ls/commit/822133bec88e5e0ddd9c9cc8d7fec67aba17f30c just yesterday.
