### ISSUE TITLE
Resolve system properties/environment variables while browsing the application.properties values

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4mp#448]
Originally reported as https://github.com/redhat-developer/intellij-quarkus/issues/1331

> It would be nice if the current System properties (eg. `user.name`) is resolved while browsing the `application.properties` values:
> ![image](https://github.com/redhat-developer/intellij-quarkus/assets/54133/87f2105d-54dd-4701-bc98-5ba38d6d4b24)

 it is supported in MP Config according to @gastaldi

`*_KEY`, `*_SECRET` and `*_PASSWORD` should be obfuscated. 

I initially started looking at an IJ implem in https://github.com/fbricon/intellij-quarkus/commit/a22b996b8a32bca298d636930f1d58e8c7a7a1c2 (validation and completion still didn't work), but this should better be done at the language server level directly.

**Comment by angelozerr** [comment]
@gastaldi once https://github.com/redhat-developer/intellij-quarkus/actions/runs/10422663550 will be finished, please install https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds to enjoy with this feature.

**Comment by gastaldi** [comment]
@angelozerr works beautifully in apps using `application.properties`, good job! 

But I noticed that it doesn't work when using `application.yaml`, is that intended?

**Comment by angelozerr** [comment]
I have not worked on that.I dont know if it will be easy to implement it.

**Comment by angelozerr** [comment]
> @angelozerr works beautifully in apps using `application.properties`, good job! 
> 

Tanks!
> But I noticed that it doesn't work when using `application.yaml`, is that intended?

**Comment by angelozerr** [comment]
> But I noticed that it doesn't work when using application.yaml, is that intended?

The YAML support is managed with a JSON Schema (we generate a JSON Schema with all properties like mp, quarkus, etc and we associate it to theyaml editor). It means that we don't manage any completion, validation, etc, we let the Editor/IDE (vscode, IJ, Eclipse IDE) supporting completion, validation.

It avoids for us to implement an fault tolerant parser for YAML which is a very hard task. As we don't manage custom completion, validation, hover, when you write {} expression in yaml value, we cannot add custom behavior,so it is impossible to manage property expression in yaml file (and System/Env properties).

The only thhing that we can do is to support System/Env as yaml key, but I'm not sure that it is interesting, right?

**Comment by gastaldi** [comment]
Thanks for investigating!

> The only th=hing that we can do is to support System/Env as yaml key, but I'm not sure that it is interesting, right?

Right, I believe they are mostly used as YAML values
