### ISSUE TITLE
CDI scope diagnostics for mp metrics @Guage 

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#46]
MP metrics `@Guage` do not support multiple instances of the underlying bean to be created, because in that case it would not be clear which instance should be used for obtaining the gauge value.  For this reason, gauges should only be used with beans that create only one instance Ie. `@ApplicationScoped` and `@Singleton`

Would be nice to provide diagnostics if a guage is incorrectly being used with a bean that could create multiple instances. 

See: https://github.com/eclipse/microprofile-metrics/blob/f9de52de9e1fe910de0f3ff1aa2949628eb1fc5a/spec/src/main/asciidoc/architecture.adoc#metrics-and-cdi-scopes

**Comment by kathrynkodama** [comment]
I can pick this up

**Comment by kathrynkodama** [comment]
We can add a diagnostic warning such that if `@Gauge` is specified and the class is annotated with `@RequestScoped`, `@SessionScoped` or `@Dependent`, we suggest they use `@ApplicationScoped`.

Tested with [Open Liberty](https://github.com/OpenLiberty/guide-microprofile-metrics) and [Quarkus](https://quarkus.io/guides/microprofile-metrics#quarkus-smallrye-metrics_quarkus.smallrye-metrics.path) implementations of MP Metrics.

The following error appears when trying to access the same request twice and the class is annotated with `@RequestScoped` or `@Dependent`:
```
A metric with metricID MetricID{name='org.acme.microprofile.metrics.PrimeNumberChecker.highestPrimeNumberSoFar', tags=[]} already exists
```

Quarkus did not throw any errors when the class was annotated with `@SessionScoped` but Open Liberty threw the below error and removed the application.  It makes sense to provide a diagnostic warning for this case as well.
```
CWWKZ0004E: An exception occurred while starting the application guide-microprofile-metrics. 
The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-000072: Bean declaring a passivating scope must be passivation capable.  
Bean:  Managed Bean [class io.openliberty.guides.inventory.InventoryManager] with qualifiers [@Any @Default]
```
