### ISSUE TITLE
Update file headers to use EPL 2.0

### ISSUE THREAD

**Issue by yeekangc** [eclipse/lsp4mp#53]
Update all necessary file headers to use the license that is selected for the project.

e.g.

 * This program and the accompanying materials are made available under the 2
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.

**Comment by angelozerr** [comment]
I think all files should respect that. Have you found a Java file which doesn't respect this rule?

The thing which is important too is to have

`* SPDX-License-Identifier: EPL-2.0`

**Comment by yeekangc** [comment]
IP review noted these as EPL 1.0.  Following up further on what more is needed.

microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/utils/DependencyUtil.java
microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/JobHelpers.java
microprofile.jdt/org.eclipse.lsp4mp.jdt.core/plugin.properties

**Comment by angelozerr** [comment]
Ok I'm working on that

**Comment by angelozerr** [comment]
@fbricon @yeekangc I have created a PR  in https://github.com/eclipse/lsp4mp/pull/54 which fixes all Java files with proper header. I think we should merge this PR now, no?
