### ISSUE TITLE
Diagnostics for mp-reactive-messaging @Incoming/Outgoing annotation

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#58]
Validate that @Incoming/Outgoing annotation are not blank. See https://github.com/eclipse/microprofile-reactive-messaging/blob/62c9ed5dffe01125941bb185f1433d6307b83c86/api/src/main/java/org/eclipse/microprofile/reactive/messaging/Incoming.java#L95

**Comment by rgrunber** [comment]
See https://github.com/eclipse/lsp4mp/issues/77 . "non-empty" seems like the kind of quick and easy support we should aim to support easily, but if it's just no possible we can always end up hard coding as before.

**Comment by JessicaJHee** [comment]
I'm interested in working on this issue!

**Comment by JessicaJHee** [comment]
I'm interested in working on this issue!
