### ISSUE TITLE
Automatically infer package names when inserting class snippets

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4mp#60]
eg:

Liveness
![image](https://user-images.githubusercontent.com/16768710/88689968-22daf400-d0c9-11ea-84b5-7a8ec0f5279c.png)
Readiness
![image](https://user-images.githubusercontent.com/16768710/88690158-57e74680-d0c9-11ea-9c99-9a7d5283055c.png)

Also JAX-RS class

See https://github.com/eclipse/lsp4mp/pull/30 and https://github.com/eclipse/lsp4mp/pull/32

**Comment by rzgry** [comment]
This would also benefit snippets included in the quarkus-ls extension. https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-java.json#L44

**Comment by angelozerr** [comment]
> This would also benefit snippets included in the quarkus-ls extension

Indeed, it's the reason why I use every time the same variable `packagename` in all JSON snippets.
