### ISSUE TITLE
Odd completion values in microprofile-config for fault tolerance project

### ISSUE THREAD

**Issue by datho7561** [eclipse/lsp4mp#65]
I get properties such as `Fallback/fallbackMethod`, `Fallback/value`... suggested in microprofile-config files.

To reproduce:

* Generate a Quarkus project from the archetype: `mvn io.quarkus:quarkus-maven-plugin:1.7.2.Final:create`
* cd into the project and add smallrye fault tolerance `./mvnw quarkus:add-extension -Dextension="smallrye-fault"`
* Create a REST resource with a get method, and set a fallback method for it:
![Screenshot from 2020-09-08 09-25-46](https://user-images.githubusercontent.com/22376627/92482606-cc77cf80-f1b5-11ea-91cc-dffb6edb4160.png)
* Open application.properties. Set the language to microprofile-config.properties
* Open completion on an empty line:
![Screenshot from 2020-09-08 09-25-51](https://user-images.githubusercontent.com/22376627/92482706-eaddcb00-f1b5-11ea-8391-54d2f63f7428.png)

**Comment by angelozerr** [comment]
I did that according to the documentation:

`Alternatively, you can configure maxRetries to be 6 for all instances of Retry in your application by specifying the property Retry/maxRetries=6.`

https://github.com/eclipse/microprofile-fault-tolerance#configuration
