### ISSUE TITLE
Move quarkus test project names to quarkus-ls repo

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#7]
Tests in quarkus-ls are using maven project name constants defined in this repo.

https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/containerimages/QuarkusContainerImagesTest.java#L35

https://github.com/eclipse/lsp4mp/blob/master/microprofile.jdt/org.eclipse.lsp4mp.jdt.test/src/main/java/org/eclipse/lsp4mp/jdt/core/BasePropertiesManagerTest.java#L78

Probably best to move them out of lsp4mp and keep them with the quarkus extension.

Also can clean up the tests projects and remove any projects that are not being used in lsp4mp. For example: https://github.com/eclipse/lsp4mp/tree/master/microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/quarkus-container-images

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/123
