### ISSUE TITLE
[MP Config 2.0] Completion for properties defined using @ConfigProperties  

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#80]
For example with a class like

```java
@ConfigProperties(prefix="server.")
@Dependent
public class Details {
    public String host; // the value of the configuration property server.host
    public int port;   // the value of the configuration property server.port
    private String endpoint; //the value of the configuration property server.endpoint
    public @ConfigProperty(name="old.location")
    String location; //the value of the configuration property server.old.location
    public String getEndpoint() {
        return endpoint;
    }
}
```

Completion options should exist for 
```
server.host = localhost
server.port=9080
server.endpoint=query
server.old.location=London
```

The prefix can also be overriden when injecting the bean annotated with `@ConfigProperties`.

Ex: 
```java
@Inject @ConfigProperties(prefix="client") Details clientDetails;
``` 
Should result in compleition options for:
```
client.host = myHost
client.port=9081
client.endpoint=shelf
client.old.location=Dublin
```

There are other cases to consider as well. More information on how properties are retrieved can be found in the spec https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc#aggregate-related-properties-into-a-cdi-bean

**Comment by angelozerr** [comment]
To verify, but if I remember Spring Boot have the same concept with Configproperties.

They manage JSPN with `groups ` insteaf of `properties` https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html#configuration-metadata-format 

I think we should so that too (generate on MicoProfile JDT side `groups `) and manage "groups" on MicroProfile LS side for completion, etc

**Comment by angelozerr** [comment]
Please note that we have managed Quarkus ConfigProperties in https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigPropertiesProvider.java but it doesn't use "groups", I think we should update on Quarkus side this provider to manage "groups".

For Quarkus side we must follow this dicussion https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.40ConfigProperties.20.20.26.20MicroProfile.20Config.202.2E0 if Quarkus Configproperties will continue to exist.

**Comment by datho7561** [comment]
FYI https://quarkus.io/version/main/guides/config-mappings#config-properties
