### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [eclipse/lsp4mp#82]
https://github.com/eclipse/lsp4mp/blob/0c8beaf50a995f683528169a1727209acfbdbdac/microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/config-quickstart/src/main/java/org/acme/config/CustomExtensionConfig.java#L12

This field is never used.

**Comment by fbricon** [comment]
This is a test asset, used to check that it's not reported as an available property.

This works as intended
