### ISSUE TITLE
Update references to Eclipse MicroProfile to just Microprofile

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#83]
When getting the announcement blog post for lsp4mp published to microprofile.io it was mentioned that the MicroProfile name stands alone without "Eclipse".

> MicroProfile stands alone as just MP, its original name under the MPWG. I have taken the liberty to cut Eclipse from the name, yet please keep in mind the name on future MicroProfile work. :)

We should update references in the readme and elsewhere from "Eclipse MicroProfile" to just "MicroProfile"

**Comment by Baibhab97** [comment]
I would like to pick this up.

**Comment by rzgry** [comment]
In the README.md file where it says "Eclipse MicroProfile" it should be changed to "MicroProfile"

Ex. the title: `Eclipse LSP4MP - Language Server for Eclipse MicroProfile` should be changed to `Eclipse LSP4MP - Language Server for MicroProfile`

**Comment by Baibhab97** [comment]
Ok. I will make the necessary changes and raise a PR. Also, except for README.md, are there any other files also where the changes should be incorporated?

**Comment by rzgry** [comment]
I did a quick search and I think it is just in the README.

**Comment by Baibhab97** [comment]
Yes, I have also checked, it's just there in the README file. I have already done the required changes and will raise the PR on October 1st, so that it counts for Hacktoberfest. You can assign the issue to me.

**Comment by rzgry** [comment]
Awesome thanks 😄

**Comment by Baibhab97** [comment]
Hi @rzgry , I have raised the PR.
