### ISSUE TITLE
Validate defaultValue of @ConfigProperty

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#90]
Validate defaultValue of @ConfigProperty  according the field type.

Given this sample:

```java
@ConfigProperty(name = "greeting.message" defaultValue="XXXXXXXXXXXXXXX")
Integer intValue;
```

We should have `XXXXXXXXXXXXXXX` which is highlighted as error because the expected value is an Integer.

This feature must be implemented on JDT LS side with the `com.redhat.microprofile.jdt.core.javaFeatureParticipants` diagnostics extension point.

As we have validation for value type in MicroProfile LS for application.properties, it should be good to move all possible validator features in the `org.eclipse.lsp4mp.microprofile.commons` package.

**Comment by rgrunber** [comment]
Relevant document on what is supported for defaultValue : https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc .
