### ISSUE TITLE
REST client CodeLens only shows up for GET annotations.

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#94]
Currently the MicroProfile REST Client CodeLens only show up for paths annotated with `@GET`.

<img src="https://user-images.githubusercontent.com/16768710/96175239-989c7200-0ef8-11eb-8f2f-b3e16cd684b1.png" width="400px" >

I think it makes sense to display them for other annotations like POST or PUT even though they cannot be accessed from the browser. (If possible maybe we could make CodeLens for POST/PUT etc. requests not clickable?) 

IE. if u have a rest client with just a POST endpoint, you might still want the CodeLens to appear so you can quickly see the full URL that is configured by your mp-config.properties file.

<img src="https://user-images.githubusercontent.com/16768710/96175440-e87b3900-0ef8-11eb-83d7-5d0224b0ce6a.png" width="400px" >

**Comment by angelozerr** [comment]
> I think it makes sense to display them for other annotations like POST or PUT even though they cannot be accessed from the browser. (If possible maybe we could make CodeLens for POST/PUT etc. requests not clickable?)

The main reason is that POST/PUT should not be clickable. I agree with you, POST/PUT CodeLens should appear but we need to manage click:

 * solution 1: when you create a CodeLens, you set the openURICommandId to null https://github.com/eclipse/lsp4mp/blob/ab86a54e2be98c20ada1664ce910a015779c6b4d/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/jaxrs/JaxRsUtils.java#L81
 * solution 2: the vscode-client is able to manage POST request. It should nice too if we could on client side manage parameters to fill wuth an UI dialog according the method parameters.

**Comment by fbricon** [comment]
if the solution to make the links not clickable is to just send a null/empty command, we should do that

**Comment by angelozerr** [comment]
> if the solution to make the links not clickable is to just send a null/empty command, we should do that

It should work.

**Comment by rgrunber** [comment]
I can have a look.

**Comment by fbricon** [comment]
codelenses are only shown on GET requests because they're the only types of requests that make sense to provide a hyperlink to

**Comment by rgrunber** [comment]
I think we can have it show up, just that we need to make it non-clickable. https://github.com/eclipse/lsp4mp/issues/94#issuecomment-709888177 mentions there is a way to do that.
