### ISSUE TITLE
Contribute to exclude property from validation

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#95]
See the issue https://github.com/redhat-developer/vscode-microprofile/issues/22

Today user can exclude properties to ignore validation with settings. This issue gives the capability to contribute for excluded properties with Java SPI.

//cc @apupier

**Comment by angelozerr** [comment]
Here my idea how to contribute to exclude validation:

 * create a file `META-INF/lsp4mp/settings.json`
 * write the settings.json file like this:

```json
{
	"validation": {
		"unknown": {
			"excluded": [
				"camel.*"
			]
		}
	}
}
```

The idea is to provide the capability to contribute another settings (not the whole) from extension.

@fbricon what do you think about this idea?

**Comment by fbricon** [comment]
interesting idea, but how do you handle conflicts between different colliding settings from different jars. Would the list of supported settings be restricted?

**Comment by angelozerr** [comment]
> interesting idea, but how do you handle conflicts between different colliding settings from different jars. 

My idea is to manage for the moment only exclude validation settings. Have you some usecase about conflicts?

Perhaps one extension exclude only `camel.*` and an another extension exclude only `camel.abcd.*`. If it that, what can we done?

> Would the list of supported settings be restricted?

Yes for the moment I would like to just take validation excluded settings. Enable codelens settings would be ignored for instance.

My initial idea is to follow the same format than user settings by filtering settings (for the moment only validation excludeded will be get)

**Comment by fbricon** [comment]
> Perhaps one extension exclude only `camel.*` and an another extension exclude only `camel.abcd.*`. If it that, what can we done?

I guess both exclusions apply (same as today), meaning camel.* will take precedence anyways

**Comment by angelozerr** [comment]
> I guess both exclusions apply (same as today), meaning camel.* will take precedence anyways

Yes exactly, so we don't manage conflicts for this validation settings excluded.
