### ISSUE TITLE
MicroProfileConfigPropertyProvider does not support @ConfigProperty on methods

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#96]
Original issue from https://github.com/redhat-developer/quarkus-ls/issues/322

I have the following class:

```java
package org.acme;

import org.eclipse.microprofile.config.inject.ConfigProperty;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class ExampleResource {

    private String myProperty;

    @ConfigProperty(name = "my.property")
    public void setMyProperty(String myProperty) {
        this.myProperty = myProperty;
    }


    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```

Seems to me this is a valid use of `@ConfigProperty` but code assist does not propose `my.property` as one of the possible keys.

**Comment by datho7561** [comment]
I don't think this is valid. This line in the spec seems to suggest it is: https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java#L115, but there are no examples of it being used, and the rest of the documentation seems to imply that it only works for fields. I tried running this in Quarkus, and it doesn't work.

**Comment by angelozerr** [comment]
@datho7561 could you check that with Quarkus team in Zulip please. Thanks!

**Comment by datho7561** [comment]
After a discussion with radcortez on the Quarkus Zulip, it seems like this is the way that you can use `@ConfigProperty` with methods:

```java
private String myProperty;

@Inject
public void setMyProperty(@ConfigProperty(name = "my.property") final String myProperty) {
    this.myProperty = myProperty;
}
```

I checked, and if you reference `my.property` this way, then it gets suggested as a key in `microprofile-config.properties`/`application.properties`.

I also found this, which is a part of the new MicroProfile 4.0 spec: (example taken from https://quarkus.io/guides/config#using-configproperties)
```java
@ConfigProperties(prefix = "greeting")
public interface GreetingConfiguration {

    @ConfigProperty(name = "message") 
    String message();

    @ConfigProperty(defaultValue = "!")
    String getSuffix(); 

    Optional<String> getName(); 
}
```

It looks like completion for this case should be covered by #80.

**Comment by datho7561** [comment]
@jeffmaury Just to clarify, were you hoping for `my.property` to appear in `application.properties`, or for completion suggestions for  `@ConfigProperty`'s `name` field?

If its the first case, I wasn't able to get the Quarkus application to run using the `@ConfigProperty` annotation on a method, and radcortez seems to think it will only work if you annotate the parameters of the method instead of the method itself.

If its the second case, we don't handle it for any instances of `@ConfigProperty` as far as I'm aware, but I could see that this could be useful and I can take a look into it.

**Comment by datho7561** [comment]
@jeffmaury just want to follow up on this issue. Could you please clarify if you meant using the `@ConfigProperty` on a method or on a parameter of a method? (I think the annotation is not valid on a method). Also, did you mean completion for the annotation field or in the `(application/microprofile-config).properties` file?

**Comment by jeffmaury** [comment]
My intent is to use the annotation on a setter method and see the property name when editing the application.properties.
Seems this is not the way it is designed

**Comment by datho7561** [comment]
Okay. Thanks for the reply. I'm going to close this and mark as invalid. If this functionality gets added to MicroProfile or Quarkus in the future, we would take a look into implementing this.

**Comment by angelozerr** [comment]
Thanks @jeffmaury for your feedback.
